spring:    
 datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
 jpa:
    generate-ddl: true
    show-sql: true 
    properties: 
     hibernate: 
      ddl-auto: update
      dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
        
server:
  port: 8085     